apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: maintnerd-deployment
spec:
  replicas: 1 # MUST BE 1 FOR NOW
  selector:
    matchLabels:
      app: maintnerd
  template:
    metadata:
      labels:
        app: maintnerd
      annotations:
        container.seccomp.security.alpha.kubernetes.io/maintnerd: docker/default
        container.apparmor.security.beta.kubernetes.io/maintnerd: runtime/default
    spec:
      serviceAccountName: maintnerd
      volumes:
      - name: maintner-cache
        persistentVolumeClaim:
          claimName: maintner-cache-claim
      containers:
      - name: maintnerd
        image: gcr.io/symbolic-datum-552/maintnerd:latest
        imagePullPolicy: Always
        command: ["/usr/bin/tini", "--", "/maintnerd", "--config=go", "--bucket=golang-maintner-log", "--verbose", "--data-dir=/cache", "--listen=:80", "--autocert=maintner.golang.org", "--autocert-bucket=golang-maintner-autocert"]
        volumeMounts:
        - mountPath: /cache
          name: maintner-cache
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            memory: "6Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prod
  name: maintner-cache-claim
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
