apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: pubsubhelper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsubhelper
  template:
    metadata:
      labels:
        app: pubsubhelper
      annotations:
        container.seccomp.security.alpha.kubernetes.io/pubsubhelper: docker/default
        container.apparmor.security.beta.kubernetes.io/pubsubhelper: runtime/default
    spec:
      serviceAccountName: pubsubhelper
      containers:
      - name: pubsubhelper
        image: gcr.io/symbolic-datum-552/pubsubhelper:latest
        imagePullPolicy: Always
        command: ["/pubsubhelper", "-autocert-bucket=golang-pubsubhelper-autocert"]
        ports:
        - containerPort: 25
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            memory: "2Gi"
