apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsubhelper-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pubsubhelper
    spec:
      containers:
      - name: pubsubhelper
        image: gcr.io/symbolic-datum-552/pubsubhelper:v4
        command: ["/go/bin/pubsubhelper"]
        ports:
        - containerPort: 25
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            memory: "2Gi"
