apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsubhelper-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pubsubhelper
    spec:
      volumes:
      - name: pv-autocert-cache
        gcePersistentDisk:
          pdName: pubsubhelper-autocert-cache
          fsType: ext4
      containers:
      - name: pubsubhelper
        image: gcr.io/symbolic-datum-552/pubsubhelper:v1
        imagePullPolicy: Always
        command: ["/go/bin/pubsubhelper"]
        volumeMounts:
        - mountPath: /autocert-cache
          name: pv-autocert-cache
        ports:
        - containerPort: 25
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            memory: "2Gi"
