apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: gerritbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerritbot
  template:
    metadata:
      labels:
        app: gerritbot
      annotations:
        container.seccomp.security.alpha.kubernetes.io/gerritbot: docker/default
        container.apparmor.security.beta.kubernetes.io/gerritbot: runtime/default
    spec:
      serviceAccountName: gerritbot
      containers:
      - name: gerritbot
        image: gcr.io/symbolic-datum-552/gerritbot:latest
        imagePullPolicy: Always
        command: ["/sbin/tini", "--", "/gerritbot", "-listen-https-selfsigned=:444", "-gitcookies-file=/gitcookies"]
        ports:
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
            ephemeral-storage: "16Gi"
          limits:
            memory: "8Gi"
            ephemeral-storage: "32Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: gerritbot-internal
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTP2"}'
spec:
  ports:
    - port: 444
      targetPort: 444
      name: https
  selector:
    app: gerritbot
  type: ClusterIP