apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: gerritbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerritbot
  template:
    metadata:
      labels:
        app: gerritbot
      annotations:
        container.seccomp.security.alpha.kubernetes.io/gerritbot: docker/default
        container.apparmor.security.beta.kubernetes.io/gerritbot: runtime/default
    spec:
      serviceAccountName: gerritbot
      containers:
      - name: gerritbot
        image: gcr.io/symbolic-datum-552/gerritbot:latest
        imagePullPolicy: Always
        command: ["/sbin/tini", "--", "/gerritbot", "-listen-http=:80", "-listen-https-autocert=:443", "-autocert-bucket=golang-gerritbot-autocert", "-gitcookies-file=/gitcookies"]
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
            ephemeral-storage: "16Gi"
          limits:
            memory: "8Gi"
            ephemeral-storage: "32Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: gerritbot
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: gerritbot
  type: LoadBalancer
  loadBalancerIP: 35.188.188.192
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: gerritbot-internal
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: gerritbot
  type: ClusterIP