# Update with
#	google_appengine/appcfg.py [-V dev-test] update .
#
# Using -V dev-test will run as dev-test.dev.golang.org.

application: golang-org
module: dev
version: main
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
- url: /favicon.ico
  static_files: static/golang.ico
  upload: static/golang.ico
  secure: always
- url: /stats
  static_files: static/stats.html
  upload: static/stats.html
  secure: always
- url: /static
  static_dir: static
  application_readable: true
  secure: always
- url: /(|dash|release|cl|stats/raw|stats/svg|stats/release|stats/release/data.js)
  script: _go_app
  secure: always
- url: /update.*
  script: _go_app
  login: admin
  secure: always
- url: /setToken
  script: _go_app
  login: admin
  secure: always
