apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: devapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devapp
  template:
    metadata:
      labels:
        app: devapp
      annotations:
        container.seccomp.security.alpha.kubernetes.io/devapp: docker/default
        container.apparmor.security.beta.kubernetes.io/devapp: runtime/default
    spec:
      serviceAccountName: devapp
      containers:
      - name: devapp
        image: gcr.io/symbolic-datum-552/devapp:latest
        imagePullPolicy: Always
        command: ["/devapp", "-listen-http=:80", "-listen-https-autocert=:443", "-autocert-bucket=golang-devapp-autocert", "-listen-https-selfsigned=:444"]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 444
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
            ephemeral-storage: "16Gi"
          limits:
            memory: "8Gi"
            ephemeral-storage: "32Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: devapp
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: devapp
  type: LoadBalancer
  loadBalancerIP: 35.188.206.122
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: devapp-internal-iap
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "build-ingress-iap-backend"}'
    cloud.google.com/app-protocols: '{"https":"HTTP2"}'
spec:
  ports:
    - port: 444
      targetPort: 444
      name: https
  selector:
    app: devapp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: devapp-internal
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTP2"}'
spec:
  ports:
    - port: 444
      targetPort: 444
      name: https
  selector:
    app: devapp
  type: ClusterIP
