apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devapp
      annotations:
        container.seccomp.security.alpha.kubernetes.io/devapp: docker/default
        container.apparmor.security.beta.kubernetes.io/devapp: runtime/default
    spec:
      containers:
      - name: devapp
        image: gcr.io/go-dashboard-dev/devapp:latest
        imagePullPolicy: Always
        command: ["/devapp", "-listen=:80", "-autocert-bucket=golang-devapp-dev-autocert"]
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            memory: "2Gi"
