runtime: go
api_version: go1.9

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /(init|buildtest|key|perflearn|_ah/queue/go/delay)
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  secure: always
