runtime: go113
service: perfdata
instance_class: F4_HIGHMEM

handlers:
  - url: /_ah/remote_api
    script: auto
  - url: /.*
    script: auto
    secure: always
env_variables:
  CLOUDSQL_CONNECTION_NAME: 'golang-org:us-central1:golang-org'
  CLOUDSQL_USER: 'root'
  CLOUDSQL_PASSWORD: ''
  CLOUDSQL_DATABASE: 'perfdata'
  GCS_BUCKET: 'golang-perfdata'
  PERFDATA_VIEW_URL_BASE: 'https://perf.golang.org/search?q=upload:'
