apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitmirror-deployment
  labels:
    app: gitmirror
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: gitmirror
  template:
    metadata:
      labels:
        app: gitmirror
    spec:
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
      containers:
      - name: gitmirror
        image: gcr.io/symbolic-datum-552/gitmirror:latest
        imagePullPolicy: Always
        env:
        - name: XDG_CACHE_HOME
          value: "/cache"
        command: ["/tini", "--", "/gitmirror", "-http=:8585", "-mirror=true", "-cachedir=/cache/gitmirror"]
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        ports:
        - containerPort: 8585
        resources:
          requests:
            cpu: "2"
            memory: "5Gi"
          limits:
            cpu: "3"
            memory: "6Gi"

