apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: coordinator-deployment
spec:
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
      annotations:
        container.seccomp.security.alpha.kubernetes.io/coordinator: docker/default
        container.apparmor.security.beta.kubernetes.io/coordinator: runtime/default
    spec:
      serviceAccountName: coordinator
      nodeSelector:
        cloud.google.com/gke-nodepool: workload-identity-pool
      containers:
      - name: coordinator
        image: gcr.io/symbolic-datum-552/coordinator:latest
        imagePullPolicy: Always
        command: ["/coordinator"]
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2222 # ssh proxy port
        - containerPort: 8123 # module proxy port (internal, not accessible directly from public)
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
