apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: gcr.io/symbolic-datum-552/coordinator:v1
        imagePullPolicy: Always
        command: ["/coordinator"]
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            memory: "2Gi"
