apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: coordinator-deployment
spec:
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
      annotations:
        container.seccomp.security.alpha.kubernetes.io/coordinator: docker/default
        container.apparmor.security.beta.kubernetes.io/coordinator: runtime/default
    spec:
      serviceAccountName: coordinator
      containers:
      - name: coordinator
        image: gcr.io/symbolic-datum-552/coordinator:latest
        imagePullPolicy: Always
        command: ["/coordinator", "-listen-http=:80", "-listen-autocert-ssh=:443", "-autocert-bucket=farmer-golang-org-autocert-cache"]
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2222 # ssh proxy port
        - containerPort: 8123 # module proxy port (internal, not accessible directly from public)
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: coordinator
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
    - port: 2222
      targetPort: 2222
      name: ssh
  selector:
    app: coordinator
  type: LoadBalancer
  loadBalancerIP: 107.178.219.46
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: coordinator-internal
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: coordinator
  type: ClusterIP
