apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: coordinator
  type: LoadBalancer
  loadBalancerIP: 104.154.113.235
