apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devappserver-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devappserver
    spec:
      containers:
      - name: devappserver
        image: gcr.io/go-dashboard-dev/devappserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            memory: "2Gi"
