apiVersion: v1
kind: Service
metadata:
  name: devappserver
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: devappserver
  type: LoadBalancer
  loadBalancerIP: 104.198.248.179